### PR TITLE
Kk user profiles

### PR DESCRIPTION
**Pull request by KeaneTK**
More user profile functions.  Merged with iteration1 before pushing.

I had two problems I couldn't figure out.  Perhaps someone with more experience could figure them out.
1. I added a profile tab to access the profile.  However, it is able to be clicked on without signing in.  I'm not sure if we'll use the navbar tabs, and if we do, how to limit access to only logged in users.
2. In the profileUpdate form, I tried to make it so that the input fields were pre-populated with the user information, but I couldn't figure out how.

Ignore the Likes.js file.  It was a prototype I made that UserMatches.js supersedes.

### CODE REVIEW

**Comment by hunz-dev** [comment]
1) This might be easier to handle once we have passport configured, because you can know a user is logged in through the 'req.user' property that will be in the request. Knowing this, we can just set constraints on the Jade template to only render certain buttons if that property is there.

2) On the server side you should fetch the data you need from the database, and then on the route which renders the webpage where the profileUpdate form is, you can pass those variables to the Jade template that is being rendered.

**Comment by sbairos** [comment]
Keane! I thought I was responsible for the profile page!!!! That's why I asked for the model and updateUser function because, I already had the profile page done!

**Comment by sbairos** [comment]
I'm going to approve this because it seems to work, but I'm probably going to swap in my profile UI stuff because I really want to keep the profile and edit profile page to be the same page. Hopefully I can make it work the way I envision it.

EDIT: I can't merge it because of conflicts with iteration1. Can you look into these Keane? Then I'll approve it.

**Comment by KeaneTK** [comment]
Remerged with iteration1, along with changes to my prototype profile pages.

Steve, if you change to your profile pages, you'll probably want to look at routes/index.js and remove my router.get('/profileForm'... code as well as profile.js/jade and profileForm.js/jade.
Iteration1's study_database.sqlite broke the code since the user table it has is not the same as the new User model.  Uncommenting the UserConnection.sync({force: true}) will rewrite the tables, but remove all current data :(

**Pull request merged**
